### ISSUE TITLE
How to create a new page template?

### ISSUE THREAD

**Issue by MussadiqKhan** [stackbit-themes/azimuth-nextjs#24]
I am trying to setup a team's page. I tried setting up a static page without setting up stackbit cms but header and footer did not show up. I tried setting up a template for stackbit cms but now luck. Any documentation>

**Comment by smnh** [comment]
Yes, we are working on improving our documentation and example repositories.

Here are some example repositories for you to start with or use as an example
https://github.com/stackbit-themes/azimuth-nextjs
https://github.com/stackbit-themes/starter-gatsby-sanity
https://github.com/stackbit-themes/gatsby-theme-intro

Take a look at stackbit documentation to learn how to configure your template site
https://www.stackbit.com/docs/stackbit-yaml/

**Comment by TomasBankauskas** [comment]
I will close this issue as no further activity occurs.

**Comment by urynon** [comment]
Hi, how to make pricing page faq cards width short? i tried to find way to adjust through `src/sass/imports/_sections.scss` //Faq section but seems not possible (note: i don't need different width for each)

![image](https://user-images.githubusercontent.com/81799342/147854769-3a759d95-1187-4397-8890-d123137c4742.png)
@TomasBankauskas
