### ISSUE TITLE
The form name contactForm is used twice

### ISSUE THREAD

**Issue by kokiscv** [stackbit-themes/azimuth-nextjs#33]
The form name `contactForm` is used for the footer's subscribe form as well as the contact page (/contact) form.
This causes Netlify to only capture the email field and ignore the rest of the fields on the contact page.

Renaming the subscribe form would fix the issue.

**Comment by TomasBankauskas** [comment]
Hi @kokiscv, the issue was fixed. Thank you for submitting it.
